# Project 1
By Alexander Hatle

In [140]:
import numpy as np
import scipy
np.random.seed(40)
#<img src="">

## Task 1
### a)

<img src="pictures/Screenshot 2022-09-19 at 11.07.35.png">

$$A = \begin{pmatrix}0 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix} \quad \text{and} \quad \vec y = \begin{pmatrix}1  \\  1\end{pmatrix}$$

<img src="pictures/Screenshot 2022-09-19 at 11.12.01.png">

$$A = \begin{pmatrix}0 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix} \quad \text{and} \quad \vec y = \begin{pmatrix}0  \\  0\end{pmatrix}$$

### b)

<img src="pictures/Screenshot 2022-09-19 at 11.14.49.png">

We know that a matrix A is symmetric if $A^T=A$ 
$$(A^{T}A)^{T}=A^{T}(A^{T})^{T} = A^{T}A \Rightarrow \text{Symmetric}$$
$$(AA^{T})^{T}=(A^{T})^{T} A^{T}= AA^{T} \Rightarrow \text{Symmetric}$$
A matrix is positive semi-definite if it satisfies
$$\vec x^{T}A\vec x \ge 0, \qquad \text{for all } x\in \mathbb{R}^{n}$$
$$\vec x^{T}A^{T}A\vec x = (A\vec x)^{T }A\vec x= ||A\vec x||^{2} \ge 0$$
$$\vec x^{T}AA^{T}\vec x=(A^{T}\vec x)^{T}A^{T}\vec x=||A^{T}\vec x||^{2} \ge 0$$
So both $A^{T}A$ and $AA^{T}$ are symmetric positive semi-definite.

In [6]:
#TODO 1b) invertibility
# mxm invertible, nxn not invertible

### c)

<img src="pictures/Screenshot 2022-09-19 at 11.35.33.png">

$$\begin{align*}
\mathcal{L}(\vec x, \vec \lambda) &= \vec x^{T}\vec x+\vec \lambda(A\vec x -\vec y)\\
&=\sum\limits_{i=1}^{n}\vec x_{i}^{2} + \lambda_{i}\left(\sum\limits_{j=1}^{m}a_{ij}x_{j}-y_{i}\right)\\
\frac{\partial \mathcal{L}}{\partial x_{k}}&=2x_{k}+\lambda_{k}\sum\limits_{j=1}^{m}a_{kj}\\
&=2x_{k}+\sum\limits_{j=1}^{m}a_{kj}\lambda_{k}\\
\nabla_{x}\mathcal{L}&=2\vec x +A^{T}\vec \lambda=0&\qquad\text{(1)}\\
\frac{\partial\mathcal{L}}{\partial \lambda_{k}}&=\sum\limits_{j=1}^{m}a_{kj}x_{j}-y_{k}\\
\nabla_{\lambda}\mathcal{L}&=A\vec x-\vec y=0 &\qquad\text{(2)}\\
\vec x&=- \frac{1}{2}A^{T}\vec \lambda\qquad&\text{rewriting (1)}\\
 A\left(- \frac{1}{2}A^{T}\vec \lambda\right)&=- \frac{1}{2}AA^{T}\vec \lambda=\vec y&\text{(1) in (2)}\quad\\
\vec \lambda&=-2(AA^{T})^{-1}\vec y\\
2\vec x +A^{T}\vec\lambda&=2\vec x-2A^{T}(AA^{T})^{-1}\vec y=0 &\text{in (2)}\\
\vec x &=A^{T}(AA^{T})^{-1}\vec y \qquad\square
\end{align*}$$

### d)

<img src="pictures/Screenshot 2022-09-19 at 12.43.09.png">

<img src="pictures/Screenshot 2022-09-19 at 12.42.42.png">

We know that  $\vec x_{min}= A^{T}(AA^{T})^{-1}\vec y$  and $Q^{T}Q=I$ since $Q$ is orthogonal.
$$AA^{T}=AQR=(Q^{T}A^{T})^{T}R=(Q^{T}QR)^{T}R=R^TR$$
$$\vec x_{min}=QR(R^{T}R)^{-1}\vec y=QRR^{-1}R^{T}\vec y$$
$$\vec x_{min}=QR^{-T}\vec y$$


In [138]:
def gramSchidt(A):
    n, m = A.shape
    Q = np.zeros((n,m))
    R = np.zeros((m,m))
    for k in range(m):
        sum = 0
        for j in range(k):
            sum += np.dot(A[:,k], Q[:,j]) * Q[:,j]
        u = A[:,k] - sum
        Q[:,k] = u / np.linalg.norm(u)
    # Make R
    for i in range(n):
        for j in range(i, m):
            R[i, j] = np.dot(A[:,j], Q[:,i])
    return Q, R

In [139]:
A = np.array([[1,5,3,2],
            [9,1,5,2]], dtype=float)
Q, R = gramSchidt(A.transpose())
print("Q\n", Q)
print("R\n", R)
print("QR\n", np.dot(Q,R))

print("--------Numpy.linalg.qr---------")
result = np.linalg.qr(A.transpose())
print("Q\n", result[0])
print("R\n", result[1])
print("QR\n", result[0]@result[1])

Q
 [[ 0.16012815  0.89458644]
 [ 0.80064077 -0.35445878]
 [ 0.48038446  0.27006383]
 [ 0.32025631  0.03375798]]
R
 [[6.244998   5.28422908]
 [0.         9.1146543 ]]
QR
 [[1. 9.]
 [5. 1.]
 [3. 5.]
 [2. 2.]]
--------Numpy.linalg.qr---------
Q
 [[-0.16012815  0.89458644]
 [-0.80064077 -0.35445878]
 [-0.48038446  0.27006383]
 [-0.32025631  0.03375798]]
R
 [[-6.244998   -5.28422908]
 [ 0.          9.1146543 ]]
QR
 [[1. 9.]
 [5. 1.]
 [3. 5.]
 [2. 2.]]


### e)

<img src="pictures/Screenshot 2022-09-19 at 14.09.50.png">

$$\begin{align*}
\vec x_{min}&= QR^{-T}\vec y\\
\text{We define}\\
\vec u&=R^{-T}\vec y \\
 \vec y &=R^{T}\vec u\\
\vec x_{min}&= Q\vec u 
\end{align*}$$
So we will use backward subtitution to find $\vec u$ and forward subtitution to find $\vec x_{min}$.


In [ ]:
def backwardAndForward(Q, R, y):
    u = scipy.linalg.solve_triangular(R.transpose(), y)

### f)
#### Compare these methods:

<img src="pictures/Screenshot 2022-09-19 at 14.16.25.png">

## Task 2
### a)

<img src = "pictures/Screenshot 2022-09-19 at 14.11.38.png">

### b)

<img src = "pictures/Screenshot 2022-09-19 at 14.12.21.png">

### c)

<img src = "pictures/Screenshot 2022-09-19 at 14.12.43.png">

### d)
#### 1)

<img src = "pictures/Screenshot 2022-09-19 at 14.13.15.png">

### 2)

<img src="pictures/Screenshot 2022-09-19 at 14.13.45.png">

## Task 3
### a)

<img src="pictures/Screenshot 2022-09-19 at 14.14.39.png">

### b)
#### 1)

#### 2)

#### 3)

### c)
#### 1)

#### 2)

#### 3)

### d)